# Source: tekton-pipeline/templates/feature-flags-cm.yaml
apiVersion: v1
data:
  await-sidecar-readiness: "false"
  coschedule: workspaces
  disable-creds-init: "false"
  disable-inline-spec: ""
  enable-api-fields: alpha
  enable-artifacts: "false"
  enable-cel-in-whenexpression: "false"
  enable-concise-resolver-syntax: "false"
  enable-kubernetes-sidecar: "false"
  enable-param-enum: "false"
  enable-provenance-in-status: "true"
  enable-step-actions: "true"
  enable-tekton-oci-bundles: "false"
  enable-wait-exponential-backoff: "false"
  enforce-nonfalsifiability: none
  keep-pod-on-cancel: "false"
  require-git-ssh-secret-known-hosts: "false"
  results-from: termination-message
  running-in-environment-with-injected-sidecars: "true"
  send-cloudevents-for-runs: "false"
  set-security-context: "false"
  set-security-context-read-only-root-filesystem: "false"
  trusted-resources-verification-no-match-policy: ignore
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: feature-flags
  annotations:
    meta.helm.sh/release-name: 'tekton-pipeline'
    meta.helm.sh/release-namespace: 'tekton-pipelines'
  namespace: tekton-pipelines
