# Source: tekton-pipeline/templates/tekton-events-controller-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-events-controller
  labels:
    app.kubernetes.io/component: events
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'tekton-pipeline'
    meta.helm.sh/release-namespace: 'tekton-pipelines'
  namespace: tekton-pipelines
