apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        skywalker2012/jenkins-x: true
        skywalker2012/jx: true
        skywalker2012/test_jx: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        skywalker2012/jenkins-x: merge
        skywalker2012/jx: merge
        skywalker2012/test_jx: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - skywalker2012/jx
        - skywalker2012/jenkins-x
        - skywalker2012/test_jx
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - skywalker2012/jx
        - skywalker2012/jenkins-x
        - skywalker2012/test_jx
      target_url: http://lighthouse-jx.jx.y.picoheart.net/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
